version: '3'

services:
  # Define a Telegraf service
  telegraf:
    image: telegraf:1.4.0
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf-configs:/etc/telegraf/telegraf.d
      - ./telegraf-scripts:/tmp/scripts
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  # Define an InfluxDB service
  influxdb:
    image: influxdb:1.3.5
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
  # Define a Chronograf service
  ## Note: this version of chronograf does not provide the ability
  ## to upload tick scripts already written
  chronograf:
    image: chronograf:1.3.8
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    links:
      - influxdb
      - kapacitor
  # Grafana dockerized info:  https://grafana.com/docs/installation/docker/
  # todo: setup data source automatically to http://influxdb:8086   no username/password
  grafana:
    image: grafana/grafana:latest
    #environment:
    #  INFLUXDB_URL: http://influxdb:8086
    #  KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "3000:3000"
    links:
      - influxdb
      - kapacitor
  # Define a Kapacitor service
  kapacitor:
    image: kapacitor:1.3.3
    volumes:
      - ./alerts:/tmp/alerts
      - ./kapacitor-tests:/tmp/kapacitor-tests
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
      - influxdb
    ports:
      - "9092:9092"
  # Define a service for using the influx CLI tool.
  # docker-compose run influxdb-cli
  influxdb-cli:
    image: influxdb:1.3.5
    entrypoint:
      - influx
      - -host
      - influxdb
    links:
      - influxdb
  # Define a service for using the kapacitor CLI tool.
  # docker-compose run kapacitor-cli
  kapacitor-cli:
    image: kapacitor:1.3.3
    entrypoint: bash
    environment:
      KAPACITOR_URL: http://kapacitor:9092
    links:
      - kapacitor
